# Generated by Django 3.2.8 on 2021-12-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211122_0516'),
        ('home', '0004_profile'),
    ]

    operations = [
    ]
